### ISSUE TITLE
Can I use this?  Is this released?

### ISSUE THREAD

**Issue by wes-goulet** [bluesliverx/disable-github-multibranch-status-plugin#1]
@bluesliverx When I search jenkins plugins I don't see this plugin, is it released?

Thanks,
Wes

**Comment by bluesliverx** [comment]
Honestly I was waiting on the jenkins hosting request, and I missed the notifications it was done.  I'm working on releasing this now, just waiting on https://github.com/jenkins-infra/repository-permissions-updater/pull/453 and then I'll need to [release it](https://wiki.jenkins.io/display/JENKINS/Hosting+Plugins#HostingPlugins-Releasingtojenkins-ci.org).

**Comment by wes-goulet** [comment]
Awesome, thanks!

**Comment by bluesliverx** [comment]
The PR was merged, but I think there must be a sync process for the permissions to actually get updated that hasn't run yet as I still do not have permissions to push it.  I'll try again this afternoon.

**Comment by bluesliverx** [comment]
@wes566, finally gave up on 1.0 and released 1.1 and it actually worked.  I see it now on the jenkins update site, so I think you should be able to use it.
