### ISSUE TITLE
How do I actually enable this plugin?

### ISSUE THREAD

**Issue by nickofthyme** [bluesliverx/disable-github-multibranch-status-plugin#3]
My apologies for such a vague question but I am very new to Jenkins and I have a multibranch pipeline I would like to disable the default status for (i.e. `continuous-integration/jenkins/pr-merge `).

I noticed in another issue post you mentioned not configuring it in the Jenkinsfile, so I would assume there would be an option to disable the status on the configuration of the multibranch pipeline, but I can't find anything. 

Lastly, I assumed that simply installing this plugin would disable the default status for all multibranch jobs on my jenkins (enterprise) instance, but yet there it is still 😞.

Please let me know if there is a configuration or step that I am missing.

Thanks!

**Comment by bluesliverx** [comment]
You need to add it as a "Behavior" when configuring the multibranch pipeline job.  In your GitHub configuration, you have the ability to add multiple behaviors to it, and it is called "Disable GitHub Notifications" in there. Once you configure it on the job, it should work fine.

**Comment by nickofthyme** [comment]
Got it perfect! Sorry for the stupid question I should have seen that.

Thanks for the plugin and the ⚡️fast reply.

## Screenshot for others to reference
![image](https://user-images.githubusercontent.com/19007109/46162871-85f26a00-c257-11e8-988b-305ab90e6677.png)

**Comment by CoryDanielson** [comment]
Any chance you could just include this image in the README? I made my way to this repo and couldn't figure out how to use the plugin. I only got here from googling "how do i use disable multibranch status" and scrolling down to the 5th result 🥴 

I found the plugin on [this website first](https://plugins.jenkins.io/disable-github-multibranch-status/), then found my way to this github repo - but still couldn't figure out how to use it (i'm a bit of a Jenkins noob, so mentioning the traits/behaviors in the README was somewhat meaningless to me)
